[package]
name = "bucket-queue"
version = "0.1.0"
edition = "2021"
authors = ["igs"]
repository = "https://www.github.com/iggedi-ig-ig/bucket-queue"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
